- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    instances:
    - mysqllll
    - backend
    - frontend
    subnet_id: subnet-0984d47e985171bd0
    sg_id: sg-01bc7ebe005fb1cb2
  tasks:
  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"